POST http://localhost:8080/clients HTTP/1.1
Content-Type: application/json

{
    "name": "Jane Doe",
    "email": "jane@doe.com"
}

###

POST http://localhost:8080/accounts HTTP/1.1
Content-Type: application/json

{
    "client_id": "4baae1e6-30e3-43f1-a206-d488adf8f324"
}

###

POST http://localhost:8080/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "d1efea6f-b37d-43dd-ae98-593d7039cf2e",
    "account_id_to": "b3dc35b4-21ae-4c23-84bf-577e508fbfed",
    "amount": 250
}